version: "3.9"

services:
  app:
    build: .
    container_name: cse3cwa_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/cse3cwa?schema=public"
      NODE_ENV: development
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npx prisma generate && npm run dev"

  db:
    image: postgres:15
    container_name: cse3cwa_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cse3cwa
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
